backend:
  name: github
  repo: dantehemerson/dcweb 

media_folder: src/pages/posts/img/
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Model, name: model, widget: hidden, default: post }
      - { label: Title, name: title }
      - { label: Description, name: description, widget: text}
      - { label: Path, name: path }
      - { label: "Featured Image", name: thumbnail, widget: image }
      - { label: Date, name: date,  widget: datetime }
      - { label: Published, name: published, widget: boolean, default: true }
      - { label: "Header Style", name: style, widget: select, options: ["default", "normal-img", "medium-img", "full-image", "doble-column"], default: default}
      - { label: Tags (Separar con comas), name: tags, widget: list }
      - { label: Body, name: body, widget: markdown }      

  - name: portfolio
    label: Projects
    folder: src/pages/projects
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: Model, name: model, widget: hidden, default: project }   
      - { label: Title, name: title }
      - { label: Subtitle, name: subtitle }
      - { label: Description, name: description, widget: text}
      - { label: Path, name: path }
      - { label: "Featured Image", name: thumbnail, widget: image }
      - { label: Date, name: date,  widget: datetime }
      - { label: Published, name: published, widget: boolean, default: true }
      - { label: "Header Style", name: style, widget: select, options: ["default", "normal-img", "medium-img", "full-image", "doble-column"], default: default}
      - { label: Tags (Separar con comas), name: tags, widget: list }

      # Datos propios de un proyecto
      - { label: Roles (Separar con comas), name: roles, widget: list }
      - { label: Stack (Separar con comas), name: stack, widget: list }
      - { label: Client, name: 'client', widget: string, default: Personal }         
      - { label: Repository, name: 'repository', widget: string }         
      - { label: Website, name: 'website', widget: string }

      - { label: Body, name: body, widget: markdown }      
      


